#where is our configuration for the server for testing
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://wohlgemuth@bitbucket.org/fiehnlab/mona-config.git

#on which port do we run
server:
  port: 1111

#we want to register the config server with eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_DISCOVERY_URI:http://localhost:8761/eureka/}
