spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.org/fiehnlab/mona-config.git

server:
  port: 1111

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${SPRING_DISCOVERY_URI:http://localhost:8761/eureka/}
