version: "3"

volumes:
  mongo-data:
  repository-data:
  downloader-data:

services:
  #
  # Databases & Messaging
  #

  mongodb:
    image: mongo:3.2.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 48
    logging:
      options:
        max-size: "100M"

  # Elasticsearch master and entrypoint
  elasticsearch_master:
    image: elasticsearch:2.4
    command: [ elasticsearch, -Des.cluster.name=mona-cluster, -Dnetwork.host=0.0.0.0, -Des.node.master=true, -Des.index.query.bool.max_clause_count=10240 ]
    ports:
      - "9200:9200"
      - "9300:9300"
    logging:
      options:
        max-size: "100M"

  # Elasticsearch node, which may be scaled
  elasticsearch_node:
    image: elasticsearch:2.4
    command: [ elasticsearch, -Des.cluster.name=mona-cluster, -Dnetwork.host=0.0.0.0, -Des.index.query.bool.max_clause_count=10240 ]
    logging:
      options:
        max-size: "100M"

  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - "15672:15672"
      - "5672:5672"
    logging:
      options:
        max-size: "100M"


  #
  # Nginx entrypoint
  #

  nginx:
    image: public.ecr.aws/fiehnlab/nginx-letsencrypt:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=mona.fiehnlab.ucdavis.edu,massbank.us
      - EMAIL=noguzman@ucdavis.edu
    volumes:
      - ./nginx_v2/certs:/etc/letsencrypt
      - ./nginx_v2/config/mona.fiehnlab.ucdavis.edu.conf:/etc/nginx/conf.d/mona.fiehnlab.ucdavis.edu.conf
      - ./nginx_v2/config/massbank.us.conf:/etc/nginx/conf.d/massbank.us.conf
    logging:
      options:
        max-size: "100M"


  #
  # MoNA base services
  #

  # The discovery service provided us with a local overview of our services
  # and allows for easy scaling and load balancing using our proxy at a later stage
  discovery:
    image: public.ecr.aws/fiehnlab/mona-discovery:prod
    ports:
      - "8761:8761"
    depends_on:
      - mongodb
      - rabbitmq
    entrypoint: bash -c "./wait-for-it.sh mongodb:27017 -t 3600 --strict -- java $JAVA_OPTS -Dspring.cloud.config.server.git.username=$GIT_USER -Dspring.cloud.config.server.git.password=$GIT_PASS -Dspring.profiles.active=docker -jar *.jar"
    environment:
      - JAVA_OPTS='-Xmx4g -XX:+UseParallelGC'
      - GIT_USER=${GIT_USER}
      - GIT_PASS=${GIT_PASS}
    logging:
      options:
        max-size: "100M"


  #
  # Initial services to start up
  #

  # Bootstrap service which pre-populated and synchronizes the databases
  bootstrap:
    image: public.ecr.aws/fiehnlab/mona-bootstrap:prod
    depends_on:
      - discovery
    entrypoint: bash -c "./wait-for-it.sh discovery:8761 -t 3600 --strict -- java -Xmx6g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"
    logging:
      options:
        max-size: "100M"

  # Webhook support to notify external apis
  webhooks:
    image: public.ecr.aws/fiehnlab/mona-webhooks-server:latest
    ports:
      - "4444:4444"
    depends_on:
      - discovery
    entrypoint: bash -c "./wait-for-it.sh discovery:8761 -t 3600 --strict -- java -Xmx4g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"
    logging:
      options:
        max-size: "100M"

  # Scheduler for curation jobs
  curationScheduler:
    image: public.ecr.aws/fiehnlab/mona-curation-scheduler:prod
    ports:
      - "5555:5555"
    depends_on:
      - discovery
    entrypoint: bash -c "./wait-for-it.sh discovery:8761 -t 3600 --strict -- java -Xmx4g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"
    logging:
      options:
        max-size: "100M"

  # Serves the content of MoNA as a repository
  repository:
    image: public.ecr.aws/fiehnlab/mona-repository:prod
    ports:
      - "8888:8888"
    depends_on:
      - discovery
    entrypoint: bash -c "./wait-for-it.sh discovery:8761 -t 3600 --strict -- java -Xmx4g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"
    volumes:
      - repository-data:/data
    logging:
      options:
        max-size: "100M"


  #
  # Persistence server, which utilizes above services, and other dependent services
  #

  # Persistence service with query interface
  persistence:
    image: public.ecr.aws/fiehnlab/mona-persistence-server:prod
    depends_on:
      - curationScheduler
    entrypoint: bash -c "./wait-for-it.sh webhooks:4444 -t 3600 --strict -- java -Xmx6g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"
    logging:
      options:
        max-size: "100M"

  # Main authentication service
  auth:
    image: public.ecr.aws/fiehnlab/mona-auth-server:prod
    depends_on:
      - curationScheduler
    entrypoint: bash -c "./wait-for-it.sh webhooks:4444 -t 3600 --strict -- java -Xmx4g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"
    logging:
      options:
        max-size: "100M"

  # MoNA similarity service
  similarity:
    image: public.ecr.aws/fiehnlab/mona-similarity:prod
    ports:
      - "9999:9999"
    depends_on:
      - curationScheduler
    entrypoint: bash -c "./wait-for-it.sh webhooks:4444 -t 3600 --strict -- java -Xmx8g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"
    logging:
      options:
        max-size: "100M"


  #
  # Proxy and additional standalone services
  #

  # The main entrypoint for MoNA
  proxy:
    image: public.ecr.aws/fiehnlab/mona-proxy:prod
    ports:
      - "8080:8080"
    depends_on:
      - persistence
    environment:
      - VIRTUAL_HOST='mona.fiehnlab.ucdavis.edu'
    entrypoint: bash -c "./wait-for-it.sh webhooks:4444 -t 3600 --strict -- java -Xss4m -Xmx4g -XX:+UseParallelGC -XX:+UseCompressedOops -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"
    logging:
      options:
        max-size: "100M"

  # Download service for scheduling and running download jobs
  downloader:
    image: public.ecr.aws/fiehnlab/mona-download-scheduler:prod
    ports:
      - "7777:7777"
    depends_on:
      - persistence
    entrypoint: bash -c "./wait-for-it.sh webhooks:4444 -t 3600 --strict -- java -Xmx8g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"
    volumes:
      - downloader-data:/data
    logging:
      options:
        max-size: "100M"

  # Run scheduled curation tasks
  curationRunner:
    image: public.ecr.aws/fiehnlab/mona-curation-runner:prod
    depends_on:
      - persistence
    entrypoint: bash -c "./wait-for-it.sh webhooks:4444 -t 3600 --strict -- java -Xmx8g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"
    logging:
      options:
        max-size: "100M"
