version: "3"

volumes:
  mongo-data:
  repository-data:
  downloader-data:

services:
  #
  # Databases & Messaging
  #

  mongodb:
    image: mongo:3.2.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 10

  # Elasticsearch master and entrypoint
  elasticsearch_master:
    image: elasticsearch:5.5
    command: [ elasticsearch, -Des.cluster.name=mona-cluster, -Dnetwork.host=0.0.0.0, -Des.node.master=true, -Des.index.query.bool.max_clause_count=10240 ]
    ports:
      - "9200:9200"
      - "9300:9300"

  # Elasticsearch node, which may be scaled
  elasticsearch_node:
    image: elasticsearch:5.5
    command: [ elasticsearch, -Des.cluster.name=mona-cluster, -Dnetwork.host=0.0.0.0, -Des.index.query.bool.max_clause_count=10240 ]

  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - "15672:15672"
      - "5672:5672"


  #
  # MoNA base services
  #

  # The discovery service provided us with a local overview of our services
  # and allows for easy scaling and load balancing using our proxy at a later stage
  discovery:
    image: public.ecr.aws/fiehnlab/mona-discovery:test
    ports:
      - "8761:8761"
    depends_on:
      - mongodb
      - rabbitmq
    entrypoint: bash -c "./wait-for-it.sh mongodb:27017 -t 3600 --strict -- java $JAVA_OPTS -Dspring.cloud.config.server.git.username=$GIT_USER -Dspring.cloud.config.server.git.password=$GIT_PASS -Dspring.profiles.active=docker -jar *.jar"
    environment:
      - JAVA_OPTS='-Xmx4g -XX:+UseParallelGC'
      - GIT_USER=${GIT_USER}
      - GIT_PASS=${GIT_PASS}


  #
  # Initial services to start up
  #

  # Bootstrap service which pre-populated and synchronizes the databases
  bootstrap:
    image: public.ecr.aws/fiehnlab/mona-bootstrap:test
    depends_on:
      - discovery
    entrypoint: bash -c "./wait-for-it.sh discovery:8761 -t 3600 --strict -- java -Xmx6g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"

  # Webhook support to notify external apis
  webhooks:
    image: public.ecr.aws/fiehnlab/mona-webhooks-server:test
    ports:
      - "4444:4444"
    depends_on:
      - discovery
    entrypoint: bash -c "./wait-for-it.sh discovery:8761 -t 3600 --strict -- java -Xmx4g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"

  # Scheduler for curation jobs
  curationScheduler:
    image: public.ecr.aws/fiehnlab/mona-curation-scheduler:test
    ports:
      - "5555:5555"
    depends_on:
      - discovery
    entrypoint: bash -c "./wait-for-it.sh discovery:8761 -t 3600 --strict -- java -Xmx4g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"

  # Serves the content of MoNA as a repository
  repository:
    image: public.ecr.aws/fiehnlab/mona-repository:test
    ports:
      - "8888:8888"
    depends_on:
      - discovery
    entrypoint: bash -c "./wait-for-it.sh discovery:8761 -t 3600 --strict -- java -Xmx4g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"
    volumes:
      - repository-data:/data


  #
  # Persistence server, which utilizes above services, and other dependent services
  #

  # Persistence service with query interface
  persistence:
    image: public.ecr.aws/fiehnlab/mona-persistence-server:test
    depends_on:
      - curationScheduler
    entrypoint: bash -c "./wait-for-it.sh webhooks:4444 -t 3600 --strict -- java -Xmx6g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"

  # Main authentication service
  auth:
    image: public.ecr.aws/fiehnlab/mona-auth-server:test
    entrypoint: bash -c "./wait-for-it.sh webhooks:4444 -t 3600 --strict -- java -Xmx4g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"

  # MoNA similarity service
  similarity:
    image: public.ecr.aws/fiehnlab/mona-similarity:test
    ports:
    - "9999:9999"
    depends_on:
      - curationScheduler
    entrypoint: bash -c "./wait-for-it.sh webhooks:4444 -t 3600 --strict -- java -Xmx8g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"


  #
  # Proxy and additional standalone services
  #

  # The main entrypoint for MoNA
  proxy:
    image: public.ecr.aws/fiehnlab/mona-proxy:test
    ports:
      - "80:8080"
    depends_on:
      - persistence
    environment:
      - VIRTUAL_HOST='mona.fiehnlab.ucdavis.edu'
    entrypoint: bash -c "./wait-for-it.sh webhooks:4444 -t 3600 --strict -- java -Xss4m -Xmx4g -XX:+UseParallelGC -XX:+UseCompressedOops -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"

  # Download service for scheduling and running download jobs
  downloader:
    image: public.ecr.aws/fiehnlab/mona-download-scheduler:test
    ports:
      - "7777:7777"
    depends_on:
      - persistence
    entrypoint: bash -c "./wait-for-it.sh webhooks:4444 -t 3600 --strict -- java -Xmx6g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"
    volumes:
      - downloader-data:/data

  # Run scheduled curation tasks
  curationRunner:
    image: public.ecr.aws/fiehnlab/mona-curation-runner:test
    depends_on:
      - persistence
    entrypoint: bash -c "./wait-for-it.sh webhooks:4444 -t 3600 --strict -- java -Xmx4g -XX:+UseParallelGC -Dspring.cloud.config.uri=http://discovery:8761/config -Dspring.profiles.active=docker -jar *.jar"
