version: '3'

services:
  mongodb:
    image: mongo:3.2.4
    ports:
      - 27017:27017

  elasticsearch:
    image: elasticsearch:2.4
    command: [ elasticsearch, -Dhttp.cors.enabled=true, -Dhttp.cors.allow-origin=* ]
    ports:
       - 9200:9200
       - 9300:9300

  elasticsearch_head:
    image: mobz/elasticsearch-head:2
    ports:
     - 9100:9100

  rabbitmq:
    image: rabbitmq:3.6-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
