version: '3'

services:
  mongodb:
    image: mongo:3.2.4
    ports:
      - 27017:27017

  elasticsearch:
    build:
        context: ./docker
        dockerfile: DockerfileElasticMaster
    ports:
       - 9200:9200
       - 9300:9300
    entrypoint: ./bin/elasticsearch

  rabbitmq:
    image:  rabbitmq:3.6-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
