version: '3'

services:
  mongodb:
    image: mongo:3.4
    ports:
      - 27017:27017

  elasticsearch:
    image: elasticsearch:5.6
    command: [ elasticsearch, -Ecluster.name=mona-cluster, -Ehttp.host=0.0.0.0, -Etransport.host=0.0.0.0, -Ehttp.cors.enabled=true, -Ehttp.cors.allow-origin=* ]
    ports:
       - 9200:9200
       - 9300:9300

  elasticsearch_head:
    image: mobz/elasticsearch-head:5
    ports:
     - 9100:9100

  rabbitmq:
    image: rabbitmq:3.7-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
