#basic configuration how to connect to the configuration server
spring:
  config:
    import: optional:configserver:${SPRING_CONFIG_URL}:http://localhost:1111
  application:
    name: persistence-service
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  profiles:
    active: default
    include:
      - mona.persistence
      - mona.persistence.init

#our local server port
server:
  port: 2222
  forward-headers-strategy: native


#basic information who we are
info:
  component: MoNA Persistence Services
