spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/metabolomics-us/mona-config
          clone-on-start: true
        default-label: PostgresqlChange

server:
  port: 1111
