#basic configuration how to connect to the configuration server
spring:
  main:
    web-application-type: reactive
  application:
    name: proxy-service
  config:
    import:  optional:configserver:http://localhost:1111
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  profiles:
    include:
      - swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

info:
  component: MoNA Edge Server

logging:
  level:
    ROOT: INFO

#on which port do we run
server:
  port: 8080

springdoc:
  swagger-ui:
    config-url: /swagger-config.json
    use-root-path: true
