#basic configuration how to connect to the configuration server
spring:
  application:
    name: query-downloader-service
  config:
    import: optional:configserver:${SPRING_CONFIG_URI}:http://localhost:1111
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        format_sql: true
        default_schema: public
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  profiles:
    active: default
    include:
      - mona.persistence
      - mona.persistence.downloader

#our local server port
server:
  port: 7777


#basic information who we are
info:
  component: MoNA Query Downloader Service
