spring:
  application:
    name: statistics-service
  config:
    import: optional:configserver:${SPRING_CONFIG_URI:http://localhost:1111}
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  profiles:
    include:
      - mona.persistence
      - swagger

#our local server port
server:
  port: 8888


#basic information who we are
info:
  component: MoNA Statistics Service