spring:
  main:
    web-application-type: none
    allow-circular-references: true
    allow-bean-definition-overriding: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        format_sql: true
        default_schema: public
        
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:/queries/spectrum_fields.sql
        - classpath:/queries/index.sql
      continue-on-error: false
