#defines the master server for synchronization against. By default this is the main mona webpage
mona:
  rest:
    server:
      host: mona.fiehnlab.ucdavis.edu
      port: 80
spring:
  cloud:
    config:
      uri:  http://localhost:1111

  rabbitmq:
    host: 127.0.0.1
  data:
    mongodb:
      host: 127.0.0.1